# Language/versions
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "10"
  - "12"

# Temporary workaround for Node 17
# See: https://nodejs.org/en/blog/release/v17.0.0/#openssl-3-0
env:
  - NODE_OPTIONS=--openssl-legacy-provider

# Notifications
notifications:
  email:
    - notify+mail@tedeh.net

after_success:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
